module.exports = [
    { name: 'paulish', tag: 'PNT' },
    { name: 'A_G_R_O_N_O_M', tag: 'PNT' },
    { name: 'sherxan', tag: 'PNT' },
    { name: 'CkuJIJIa_HET', tag: 'PNT' },
    { name: 'Kira-5let', tag: 'PNT' },
    { name: 'K_H_9l_3_b-T_b_M_bl', tag: 'PNT' },
    { name: 'Whisky', tag: 'PNT' },
    { name: 'npocmume', tag: 'PNT' },
    { name: 'XpAHuTeJlb_3oJl0Ta', tag: 'PNT' },
    { name: 'kratasuk85', tag: 'PNT2' },
    { name: '6eru_OT-MeH9l', tag: 'PNT2' },
    { name: 'evgen150rus', tag: 'PNT2' },
    { name: 'egor55555_tankist', tag: 'PNT2' },
    { name: 'AZESHAJPER', tag: 'PNT2' },
    { name: 'xxx_LLI_u_x_a_H_xxx', tag: 'PNT2' },
    { name: 'JART_7', tag: 'PNT2' },
    { name: 'KaBka3ckuu_TIJIeHHuk', tag: '-' },
    { name: 'KyKoJIkA', tag: '-' },
    { name: 'D_O_H_6_A_C_C', tag: '-' },
    { name: 'olga7410', tag: '-' },
    { name: 'AleAnA', tag: '-' },
    { name: 'Mex1111.ru', tag: '-' },
    { name: 'SWALLOW_THE_SUN', tag: '-' }
];
